### PR TITLE
Related products

### PR DESCRIPTION
**Pull request by getdatakick**
Implementation of related products feature. @Traumflug could you please review, as it's quite a big piece of change?

### CODE REVIEW

**Comment by selwynorren** [comment]
This looks amazing, I am very excited about this feature

**Comment by Traumflug** [comment]
I'd simply trust this work :-)

- An upgrade script for 2.0.0 might be some peek into the future, like a preparation for some feature yet to come ... and now abandoned with the developer disappearing. Which means, removing this script is fine.
- Does this https://github.com/thirtybees/beesblog/pull/34/commits/78d4166dd074ee37cfdf77980089bfd3498f360a create yet another submodule? I'm not enthusiastic about the strategy to create multiple modules with one install, such stuff is hard to remove when no longer needed. But I didn't find a better solution yet, either.
- Version bump usually happens together with making the release, so this commit is a bit early.

**Comment by Traumflug** [comment]
Thinking about the reset-without-delete thing: do merchants recognize this feature? Not sure about this, because all other modules make a full reset. I might be a better solution to add a _Reset_ button onto the configuration page, doing the same.

**Comment by getdatakick** [comment]
Regarding reset: this just provides the ability for merchants to decide if they want soft or hard reset. When this `reset` method exists, thirtybees will show this popup when merchant click on Reset module:

image

I think it would be better to have distinct menu entries for hard and soft reset, and not combine it under one reset menu item:

image

**Pull request merged**
