### PR TITLE
changing invalid active param to valid for post lookup

### PR DESCRIPTION
**Pull request by slvrspiral**

### CODE REVIEW

**Comment by firstred** [comment]
Hmmz, isn't the `sqlWhere + active` just a repeat of the `where + active` right above it?

**Comment by slvrspiral** [comment]
You are correct.  However, the line I was trying to fix needs to be removed as lang_active is an invalid column.

**Comment by firstred** [comment]
Hmmz, wasn't it supposed to have a language restrictrion somewhere? Like id_lang = $idLang. (Am on my phone atm, can't examine the whole function)

**Comment by getdatakick** [comment]
I've investigated. The sql generated by core PrestaShopCollection class is valid. Sql contains lang table, which contains lang_active column -- everything is in order.

**Pull request closed without merging**
