### PR TITLE
Collection of changes

### PR DESCRIPTION
**Pull request by selwynorren**
The beesblog template for showing the amount of posts required 4 columns so when there is 5 being drawn it show the fifth on a new row. The amount for the columns is left unchanged.

### CODE REVIEW

**Comment by firstred** [comment]
Looks good to me. Thanks!

**Review by selwynorren — COMMENTED** [review]
A whole bunch of changes have been made to the blog system, each change has a full commit message

**Comment by selwynorren** [comment]
Awesome thanks so much

**Comment by firstred** [comment]
You're welcome and thanks again for your help!

**Comment by selwynorren** [comment]
Absolute Privilege, Thx

**Pull request merged**
