### PR TITLE
Added support for updateFriendlyURL()

### PR DESCRIPTION
**Pull request by yaniv14**
Right now admin.js throw an error when entering Blog post title due to missing ```PS_ALLOW_ACCENTED_CHARS_URL``` variable.

Blog category name not even trying to populate URL rewrite.

### CODE REVIEW

**Comment by getdatakick** [comment]
Thank you for the contribution. I have picked modified version of your fix to the codebase - see commit  6022b479caafbad1f06b0c63cc7d5d20e72ec20a

**Comment by yaniv14** [comment]
@getdatakick Are you sure that all changes were merged?
I dont see the tpl files in the master repo.

**Comment by getdatakick** [comment]
I didn't merge your pull request, I used it as a basis for different fix.

The reason why you added helper overrides was to inject javascript variable into the page. There's a better way to do that - use `Media::addJsDef` method

**Comment by yaniv14** [comment]
Perfect.
There should be other places where you can use that approach, because originally I took that part of the code from other templates i found.

**Pull request closed without merging**
